---
title: "HW02_Assignment1"
output:
    html_document:
      keep_md: true
editor_options: 
  chunk_output_type: inline
---

```{r allow errors, echo = FALSE}
knitr::opts_chunk$set(error = TRUE)
```

```{r load packages, warning = FALSE, message = FALSE}
library(gapminder)
library(tidyverse)
```

Exercise 1.1
Complete exercise and put into new variable
```{r}
(gapminder_new = gapminder %>% 
  filter(year >= 1970 & year < 1980,
         country == "China" | country == "Croatia" | country == "Haiti"))
```

Exercise 1.2 

Select country and gdppercap
```{r}
gapminder_new %>% 
  select(country, gdpPercap)
```

Exercise 1.3

```{r}
gapminder %>% 
  arrange(country, year) %>% 
  mutate(laglifeExp = lag(lifeExp,1)) %>% 
  mutate(changeinlifeExp = lifeExp-laglifeExp)%>% 
  filter(changeinlifeExp<0) %>% 
  filter(year!=1952)
```

Exercise 1.4 

```{r}
gapminder %>% 
  group_by(country) %>% 
  summarize(maxgdp = max(gdpPercap))
```

Exercise 1.5

```{r, fig.width = 5, fig.height = 2}
gapminder %>% 
  filter(country == 'Canada') %>% 
  arrange(year,lifeExp) %>%
  ggplot(aes(lifeExp,gdpPercap)) +
  geom_line() +
  scale_y_continuous(name = "GDP of Canada",limits = c(10000,40000)) +
  scale_x_continuous(name = 'Life Expectancy', limits = c(68,81))
  
  
```

